Process meeting to activities
eminx/cocoso pull request #53
Opened 2022-05-10 12:39 UTC by ilkergonenc

Process Meetings methods and data moved to Activities.

2022-05-10 12:59 UTC, eminx commented
The solution doesn't include any fix on the activities page to render on the program. 
The same probably goes on the calendar page.

2022-05-10 13:03 UTC, eminx commented
Process admin doesn't seem to be able to see the list of attendees...

2022-05-10 13:04 UTC, eminx requested changes

2022-05-10 13:04 UTC, eminx commented on imports/api/activities/activity.js
>    isRegistrationDisabled: { type: Boolean, optional: true }, // undefined
can we delete //undefined?

2022-05-10 13:04 UTC, eminx commented on imports/api/activities/activity.js
> +import { boolean } from 'joi';
not used anywhere...

2022-05-10 13:04 UTC, eminx commented on imports/ui/pages/processes/Process.jsx
> +      isRegistrationDisabled: true,
should probably be true if we want to enable rsvp

2022-05-10 13:04 UTC, eminx commented on imports/ui/pages/processes/Process.jsx
> +  toggleAttendance = (meetingId, meetingIndex) => {
for the naming sake, I think we shouldn't use `meetingId`, and instead use `activityId`

2022-05-10 13:04 UTC, eminx commented on imports/ui/pages/processes/Process.jsx
> +  toggleAttendance = (meetingId, meetingIndex) => {
Because there's no such thing as meeting in the db..

2022-05-10 13:04 UTC, eminx commented on imports/ui/pages/processes/Process.jsx
> +  deleteMeeting = (meetingId, meetingIndex) => {
the same

2022-05-10 13:04 UTC, eminx commented on imports/ui/pages/processes/Process.jsx
> +    Meteor.call('deleteActivity', meetingId, (error, respond) => {
same

2022-05-10 13:04 UTC, eminx commented on imports/ui/pages/processes/ProcessContainer.jsx
> +  });
Please revise this code, like below: 
```
if (!activity.datesAndTimes || activity.datesAndTimes.length === 0) {
  return;
}
return {
  ...
}
```

2022-05-10 14:51 UTC, ilkergonenc commented on imports/api/activities/activity.js
>    isRegistrationDisabled: { type: Boolean, optional: true }, // undefined
I checked schemas on compass analyse and some were never used so analysed as undefined by compass and I commented them ... so i think they can be cheked and deleted

2022-05-10 15:32 UTC, ilkergonenc commented on imports/api/activities/activity.js
>    isRegistrationDisabled: { type: Boolean, optional: true }, // undefined
for now I disabled some unused keys to test and delete

2022-05-11 11:56 UTC, eminx approved these changes

2022-05-11 14:04 UTC, merged